### ISSUE TITLE
Feature: Spring Boot Starter

### ISSUE THREAD

**Issue by jonathanlukas** [camunda-community-hub/camunda-operate-client-java#14]
In alignment with `spring-zeebe`, there could be a spring boot starter for the Operate client as well.

It should:

* Allow configuration of the client using properties or yaml
* support all types of authentication as well
* expose a bean of type `CamundaOperateClient`

**Comment by falko** [comment]
If you're using Spring Zeebe, there is already an Operate Client included.

**Comment by chDame** [comment]
hi Jonathan,

the spring zeebe pom referencing this project:
https://github.com/camunda-community-hub/spring-zeebe/blob/master/pom.xml

**Comment by jonathanlukas** [comment]
Thank you for the feedback. 

I had to dig until I found it. It is part of the inbound connector runtime. Could we clarify this somewhere?

**Comment by berndruecker** [comment]
This is kind of the in-flux state, see also https://github.com/camunda-community-hub/spring-zeebe/issues/245. We haven't finally ddecided how to go about it exactly and if we want to expose to every spring-zeebe user or if it should be an additional dependency. 

Further context is also the restructuring we plan for spring-zeebe discussed here: https://github.com/camunda-community-hub/spring-zeebe/issues/275. I hope we come to this soon - but can't promise.

Input always appreciated @jonathanlukas!

**Comment by jonathanlukas** [comment]
From my point to view, we should treat the clients and the platform architecture equal:
Zeebe can be used independent of Operate, so the clients should exist next to each other. This also pays respect to our current approach of offering Operate enterprise-only in production.
A Zeebe community user will have no use for an Operate client that potentially increases artifact size and could expose additional vulnerabilities.
A Zeebe enterprise would still be able to pick a `camunda-platform-8-client-spring-boot-starter-all` dependency that bundles everything.
To enable this scenario and make it as user-friendly as possible, I would align the major concepts like naming conventions, properties structure, resilience behaviour ...

**Comment by berndruecker** [comment]
See https://github.com/camunda-community-hub/spring-zeebe/blob/main/spring-boot-starter-camunda/src/main/java/io/camunda/zeebe/spring/client/CamundaAutoConfiguration.java#L38 - I think this closes the issue for now - WDYT @jonathanlukas?

**Comment by jonathanlukas** [comment]
lgtm
