### ISSUE TITLE
Feature: Support `searchAfter` when searching

### ISSUE THREAD

**Issue by spalberg** [camunda-community-hub/camunda-operate-client-java#15]
Currently it looks like `searchAfter` is not supported for searches. Since the maximum page size of Operate is limited to 1000, this means that you may not be able to get all the elements. 

Also, it would generally make sense to make this search option available - just like `sortValues` in the search results.

**Comment by chDame** [comment]
Hi Sven,

Many thanks for your feedback. It's indeed a very interesting topic and I just opened a PR and I'll wait the feedbacks from Bernd. If it's ok, I'll release it and ping you in this thread.

Link to the PR : https://github.com/camunda-community-hub/camunda-operate-client-java/pull/17

**Comment by chDame** [comment]
Hi Sven,

this is released in 1.3.8,

Thanks again!
