### ISSUE TITLE
Should `searchProcessDefinitions` return empty List instead of null?

### ISSUE THREAD

**Issue by berndruecker** [camunda-community-hub/camunda-operate-client-java#18]
Context: https://github.com/camunda-community-hub/spring-zeebe/issues/288

We see regular NPE with the result of this query:

`camundaOperateClient.searchProcessDefinitions(processDefinitionQuery);`

MY expectation was, that this query will return an empty list if no process definitions are found. Is that assumption wrong or is that a bug?

@chDame - do you know?

**Comment by chDame** [comment]
Hi Bernd,

It's the result returned by the API that is empty. To avoid such problem, we could provide an empty list in the client if the result is null. What do you think ?

**Comment by berndruecker** [comment]
Interessting enough, we saw a NPE in spring-zeebe (which I now catch explicitly https://github.com/camunda-community-hub/spring-zeebe/commit/47e151387040920b30c8914297fe084bc37cb00c)
