### ISSUE TITLE
Auth secrets are leaked in exception message

### ISSUE THREAD

**Issue by chillleader** [camunda-community-hub/camunda-operate-client-java#25]
During the authentication attempt, if the auth server responds with status code >= 400, response body is copied over to the exception message, resulting in a potential leak of credentials in logs.

### Steps to reproduce

1. Configure Operate authentication so that the authentication request fails (e.g. use an invalid token endpoint URL to receive 404)
2. Start an application that creates an instance of `CamundaOperateClient` on startup.
3. Verify that logs contain a similar entry:
```
io.camunda.operate.exception.OperateException: /oauth/token : 404 Not Found; Body : {"grant_type":"client_credentials", "audience":"operate.camunda.io", "client_id": "real-client-id", "client_secret":"real-client-secret"}
```
The `client-id` and `client-secret` contain actual credentials.

### Expected behavior

The request body is not stored in auth-related exceptions to avoid the leaks of sensitive data in the logs.

**Comment by igpetrov** [comment]
Fixed at https://github.com/camunda-community-hub/camunda-operate-client-java/commit/a40648280a8a0d4fc6ad9bfcf4d4b0bd8525fa8c

**Comment by igpetrov** [comment]
Already on maven central
https://repo.maven.apache.org/maven2/io/camunda/camunda-operate-client-java/8.1.7.2/
