### ISSUE TITLE
FlownodeInstanceFilter doesn't match to request fields

### ISSUE THREAD

**Issue by NewbieProger** [camunda-community-hub/camunda-operate-client-java#28]
![image](https://user-images.githubusercontent.com/34659664/232749021-3795ce92-f67d-45c9-8828-bc6bbd25b19c.png)

![image](https://user-images.githubusercontent.com/34659664/232749053-b28f91b6-8524-4764-b559-04dcd037d918.png)

for example, where is processDefinitionKey ?

**Comment by NewbieProger** [comment]
https://github.com/camunda-community-hub/camunda-operate-client-java/pull/29

**Comment by chDame** [comment]
released in 8.1.8
