### ISSUE TITLE
Endpoints which contains "state" in filter doesn't filter by INCIDENT state

### ISSUE THREAD

**Issue by NewbieProger** [camunda-community-hub/camunda-operate-client-java#30]
![image](https://user-images.githubusercontent.com/34659664/233435287-62ff67ea-d5b7-4a41-aa42-9f4028f4d8dc.png)
![image](https://user-images.githubusercontent.com/34659664/233435444-989f45cb-db25-46d2-a7ab-d05282a36e8f.png)

**Comment by chDame** [comment]
Hi @NewbieProger,

You're right. The states are only ACTIVE, COMPLETED and CANCELED. The client code should be corrected. For incidents, you should use the incident search.

**Comment by chDame** [comment]
released in 8.1.8
