### ISSUE TITLE
Fetching tasks through operate

### ISSUE THREAD

**Issue by michals96** [camunda-community-hub/camunda-operate-client-java#40]
Hey guys.

Lately I've been using this java client for some development. In one of our projects we have reached a corner case where we might need to get rid of tasklist entirely. We were using tasklist client in order to fetch tasks (https://github.com/camunda-community-hub/camunda-tasklist-client-java).

**Q1**: Is it possible to fetch tasks through Operate if we get rid of tasklist? It looks like this operate-client does not support it, but essentialy if it's possible, then we could also get involved in developing such feature as we might need it.

**Q2**: This might be offtopic, but we might even need to get rid of Operate in future and use Zeebe only. Is there any reliable way to fetch tasks in this scenario?

Thanks in advance.

**Comment by jonathanlukas** [comment]
Please have a look at the Operate API: https://docs.camunda.io/docs/apis-tools/operate-api/overview/

There is no way to fetch tasks from here. Tasklist is the API for this.
