### ISSUE TITLE
`SimpleAuthentication` expect only one cookie in the response and therefore fails when other cookies are present.

### ISSUE THREAD

**Issue by blondacz** [camunda-community-hub/camunda-operate-client-java#42]
__Describe the Bug__

`SimpleAuthentication` expects only one cookie in the response and therefore fails when other cookies are present.
 This can happen for instance when infrastructure adds extra headers for tracking.

[SimpleAuthentication](https://github.com/camunda-community-hub/camunda-operate-client-java/blob/main/src/main/java/io/camunda/operate/auth/SimpleAuthentication.java#L49C5-L49C5)
The code bellow expects exactly one header with "Set-Cookie" key.
```java
String cookie = response.getHeader("Set-Cookie").getValue();
```

__Steps to Reproduce__

1. Use simple authentication with Operate behind proxy that sets additional cookies.

__Expected Behavior__
Get all cookies and find one that has key of `OPERATE_SESSION`

__Environment__

- Camunda version: 8.3.0 (self-managed)

**Comment by chDame** [comment]
Hi @blondacz,

I'm sorry but I've very limited bandwidth at the moment. Could the SelfManagedAuthentication (against keycloak) be a better fit  for you? If not, would you mind opening a PR that I could review to fix the issue ? If not, I'll try to do it later :)
