### ISSUE TITLE
Jar are not present in Maven

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda-community-hub/camunda-operate-client-java#65]
**Describe the bug**

Library are not in Maven Central.
In Maven Central, the last version is 8.3.0.1 where the pom.xml is 8.5.9-rc2-SNAPSHOT

In 
https://mvnrepository.com/artifact/io.camunda/camunda-operate-client-java
Maven Central:

<dependency>
    <groupId>io.camunda</groupId>
    <artifactId>camunda-operate-client-java</artifactId>
    <version>8.3.0.1</version>
</dependency>

Documentation:
```
<dependency>
  <groupId>io.camunda.spring</groupId>
  <artifactId>java-client-operate</artifactId>
  <version>${version.operate-client}</version>
</dependency>

```
Please provide JAR in Maven.

**Expected behavior**

JAR are present in Maven

**Comment by jonathanlukas** [comment]
The Operate client is documented [here](https://github.com/camunda-community-hub/camunda-operate-client-java?tab=readme-ov-file#plain-java):

In general, it can be fetched from maven using these parameters:
```xml
<dependency>
  <groupId>io.camunda.spring</groupId>
  <artifactId>java-client-operate</artifactId>
  <version>${version.operate-client}</version>
</dependency>
```
While the last released artefact from this repository is `8.3.x`, you can actually look into [`8.5.9-rc1`](https://github.com/camunda-community-hub/camunda-operate-client-java/releases/tag/8.5.9-rc1) which is the latest release from this repository. But as it is a pre-release, it is not shown too popular.
