### ISSUE TITLE
POM 8.5 release referenced 8.5.9-rc2-SNAPSHOT which not exist.

### ISSUE THREAD

**Issue by pierre-yves-monnet** [camunda-community-hub/camunda-operate-client-java#66]
**Describe the bug**

I'm using 8.5.9-rc2-SNAPSHOT as describe in the https://github.com/camunda-community-hub/camunda-operate-client-java/blob/release/8.5/pom.xml

This library does not exist in MAKEFILE or in JFROG.
I found 8.5.8-rc2-20240805.051418-2 in JFROG

**Expected behavior**

it seem  8.5.8-rc2-20240805.051418-2 is the last available JAR.

The POM give  8.5.9-rc2-SNAPSHOT, this library must be available.

Note 1:
There is a 8.5.8 version available in JFROG. This version does not contains io.camunda.operate.auth package. Because it is not synchronized to the README, this version should be deleted

Note 2 : the main show in the POM 

`  <version>8.6.0-alpha1-SNAPSHOT</version>`

This version (8.6) is not available. This should not be in the main project, maybe in a different branch, waiting for the 8.6 release? What's happen if I use a 8.6 version on my 8.5 Zeebe Engine?

**Comment by jonathanlukas** [comment]
`8.5.9-rc2-SNAPSHOT` is the snapshot version BEFORE the next release (which will be `8.5.9` or `8.5.9-rc2` based on the feedback of the connectors team).

Please use `8.5.9-rc1` in the meantime which is available on [maven central](https://mvnrepository.com/artifact/io.camunda.spring/java-client-operate/8.5.9-rc1).
